### ISSUE TITLE
Remove vertical lines from the plot d3.js

### ISSUE THREAD

**Issue by matejamateusz** [alexpearce/histograms#10]
Hey Alex, 
![obraz](https://cloud.githubusercontent.com/assets/6429539/7994658/5a9d6902-0b0f-11e5-8347-14c7f16234a0.PNG)
I want to remove the lines (they are not values) crossed in the attached picture. Thank you very much in advance for help.

**Comment by alexpearce** [comment]
I have the idea of adding a extra configuration flag to the `Histogram` potable, something like this

```
myChart.addPlotable(d3.plotable.Histogram('myData', myData, {closed: false}));
```

which produces this:

![Open histogram, with no bin edges in the lowest and highest bins](https://cloud.githubusercontent.com/assets/540853/7994729/0014adfa-0b10-11e5-88c5-4b7956c181d6.png)

Is that the effect you're after?

**Comment by matejamateusz** [comment]
Unfortunately, it not changed anything in my plots;/

**Comment by alexpearce** [comment]
That's because I'm only playing around with the code on my local machine :smile:

If this is the effect you're after, I can commit the changes to this repository, and then you can download the new script and see for yourself.

**Comment by matejamateusz** [comment]
I see. Yeah i want this effect but when i changed this adding {closed:
false} unfortunately not working. Ok looking forward for that as soon as it
can possible;) Thank you very much;)

Cheers,

MJM

**Comment by alexpearce** [comment]
You won't be able to use `{closed: false}` yourself because there are changes needed to the code, and I've only made those changes on my local machine.

I will commit them here shortly.

**Comment by matejamateusz** [comment]
Ok waiting for that:)

Greetings

MJM

2015-06-04 23:29 GMT+02:00 Alex Pearce <notifications@github.com>:

**Comment by matejamateusz** [comment]
![zrzut ekranu z 2015-06-04 23 52 40](https://cloud.githubusercontent.com/assets/6429539/7995623/0117db02-0b18-11e5-810c-7eb1a535e3b8.png)
Ok I have sth like this but hopefully is because i didn't changed everything. Could you make the master? I think this is the best option ;) Cheers, MJM

**Comment by matejamateusz** [comment]
![zrzut ekranu z 2015-06-05 00 31 27](https://cloud.githubusercontent.com/assets/6429539/7995845/4d529550-0b1a-11e5-8f09-fdc6cdc9f120.png)

Ok, it is working! Thank you very very much ;) You have a very good Polish beer on me ;)

Cheers,

MJM
