### ISSUE TITLE
Input data for line chart

### ISSUE THREAD

**Issue by matejamateusz** [alexpearce/histograms#12]
Hey Alex again ;) I want to ask because for the histogram plot there is no problem with input data by the function: 
// Manipulate the input data to a format accepted by the Histogram chart
  var formatData = function(data) {
    var rtn = [];
    for (var i = 0; i < data['values'].length; i++) {
      var bins = data['binning'][i];
      rtn.push({
        xlow: bins[0],
        xhigh: bins[1],
        y: data['values'][i],
        yerr: data['uncertainties'][i]
      });
    }
    return rtn;
  };

What about if I want the input data for line chart where you have: 

line = [
        {x: -6, y: 0.4, xerr: [0.3, 0.3], yerr: [0.1, 0.1]},
        {x: -4, y: 0.6, xerr: [0.3, 0.3], yerr: [0.1, 0.1]},
        {x: -2, y: 0.4, xerr: [0.3, 0.3], yerr: [0.1, 0.1]},
        {x: 0, y: 0.0, xerr: [0.3, 0.3], yerr: [0.1, 0.1]},
        {x: 2, y: 0.2, xerr: [0.3, 0.3], yerr: [0.1, 0.1]},
        {x: 4, y: 0.8, xerr: [0.3, 0.3], yerr: [0.1, 0.1]},
        {x: 6, y: 0.6, xerr: [0.3, 0.3], yerr: [0.1, 0.1]}
      ];

in a separate file (f.e. line.js)?

Thank you in advance ;)

**Comment by alexpearce** [comment]
You will need to manipulate the data you have in to the format that is used by `Histogram`.

**Comment by matejamateusz** [comment]
You mean accepted by this formatData function?

**Comment by alexpearce** [comment]
No, `formatData` takes data in some format (produced by some program I used a long time ago) and converts it in to a format that `Histogram` accepts. So, you need to create a similar function that converts the data you have now in to something that looks like the _output_ of `formatData`.

**Comment by matejamateusz** [comment]
Ok. And then I have to plot by d3.plotable.LineChart or 
d3.plotable.Histogram ?

W dniu 08.06.2015 o 15:24, Alex Pearce pisze:

**Comment by matejamateusz** [comment]
Ok. And then I have to plot by d3.plotable.LineChart or d3.plotable.Histogram because I want a linear plot not histogram plot? ![obraz](https://cloud.githubusercontent.com/assets/6429539/8036339/8d3636f6-0df7-11e5-978f-2d3b19f45c7d.png)

**Comment by alexpearce** [comment]
If you don't want a histogram then `Histogram` is not for you :smile:

**Comment by matejamateusz** [comment]
Yeah :D I want Linear plot as it in the picture (bould be taken in the same
format as for histogram (json) or in other) but from separate file.

2015-06-08 16:03 GMT+02:00 Alex Pearce <notifications@github.com>:

**Comment by alexpearce** [comment]
If you want a line plot then you could use `d3.plotable.LineChart`. The format for the input data is explained in the [“Data API” of the doctstring](https://github.com/alexpearce/histograms/blob/master/src/d3.plotable.LineChart.js#L6-L17).

**Comment by matejamateusz** [comment]
Ok, thanks ;)

**Comment by matejamateusz** [comment]
//Manipulate the input data to a format accepted by the Linear chart for scatter plot
var formatData2 = function(data) {
    var rtn = [];
    for (var i = 0; i < data['y'].length; i++) {
      rtn.push({
        x: data['x'][i],
        xerr: data['xerr'][i],
        y: data['y'][i],
        yerr: data['yerr'][i]
      });
    }
    return rtn;
  };


  // Generate some line chart data
  var line = formatData2(scatterData)


I think this is a right one, it works ;)

**Comment by alexpearce** [comment]
Excellent! Feel free to close this issue if you're happy this is solved.
