### ISSUE TITLE
Remove interpolation

### ISSUE THREAD

**Issue by matejamateusz** [alexpearce/histograms#13]
lineChart.addPlotable(d3.plotable.LineChart('line', line, {showPoints: true, showUncertainties: true, interpolation: 'linear', color: 'red'}));

I've seen the link https://github.com/mbostock/d3/wiki/SVG-Shapes#line_interpolate but still how to remove the interpolation? I want just Uncertainties and Points

Cheers

MJM

**Comment by alexpearce** [comment]
Maybe plotting a set of points would be a good candidate for creating a new `plotable`?

**Comment by matejamateusz** [comment]
So there is no way to edit the LineChart for removing the interpolation?

**Comment by matejamateusz** [comment]
Or maybe create the trick that the interpolation would be transparent?

**Comment by alexpearce** [comment]
You could set the opacity of the line to zero:

```css
.LineChart .line {
    opacity: 0;
}
```

**Comment by matejamateusz** [comment]
Thank you very much ;)
